
import sys
import traceback
try:
    from alembic.config import Config
    from alembic import command
    alembic_cfg = Config('alembic.ini')
    from alembic.util.exc import AutogenerateDiffsDetected
    command.check(alembic_cfg)
except AutogenerateDiffsDetected as e:
    with open('alembic_err6.txt', 'w') as f:
        f.write(str(e))
except Exception as e:
    with open('alembic_err6.txt', 'w') as f:
        traceback.print_exc(file=f)

