"""Add confirmed flag to project files

Revision ID: 0754d9a91fce
Revises: 0f7721a6fe50
Create Date: 2026-02-27 16:12:19.229680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0754d9a91fce'
down_revision: Union[str, None] = '0f7721a6fe50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_files', sa.Column('confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_files', 'confirmed')
    # ### end Alembic commands ###
