"""Add color and icon to project

Revision ID: 0f7721a6fe50
Revises: ffff55f4aceb
Create Date: 2026-02-27 13:36:20.633466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7721a6fe50'
down_revision: Union[str, None] = 'ffff55f4aceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('color', sa.String(length=100), nullable=False))
    op.add_column('projects', sa.Column('icon', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'icon')
    op.drop_column('projects', 'color')
    # ### end Alembic commands ###
